% This file tests the network learnt by networkTraining.m with the testing
% data generated by generateTestData.m.

%% Data preparation
% Data splitting
initialRunlength = 100;
testRunlength = 1e5;

outputCollectMat = zeros(testRunlength, 1);
totalstate =  zeros(totalDim,1);    
internalState = totalstate(1:internalLength);

fprintf('Start testing...\n');

%% Scanning through testing data
for i = 1:initialRunlength + testRunlength
    in = testIn(1,i);
    totalstate(internalLength+1:internalLength+inputLength) = in;
    internalState = [intWM, inWM, ofbWM]*totalstate;
    netOut = outWM' * [internalState;in];
    totalstate = [internalState;in;netOut];
    
    % Collect output
    if i > initialRunlength
        outputCollectMat(i - initialRunlength,1) = netOut;
    end
end

%% Detector
detectedBlock = repmat(outputCollectMat',length(symbols),1);
referenceBlock = repmat(symbols',1,testRunlength);
distance = abs(detectedBlock - referenceBlock);
[y,ind] = min(distance);
detectedSymbols = symbols(ind);

% Symbol error rate computation
numOfErrors = sum(detectedSymbols ~= testOut(initialRunlength+1:initialRunlength+testRunlength));
SER = numOfErrors ./ testRunlength;

%% Result visualization
fprintf('Testing completed!\n');
fprintf('SER = %f\n', SER);